<footer>
	<div>
		<aside>PRECIOS COTIZADOS EN PESOS, SUJETOS A MODIFICACIONES SIN PREVIO AVISO. | COPYRIGHT© 2015 FLOPY SYSTEM TODOS LOS DERECHOS RESERVADOS.</aside>
		<span>DESIGN BY FLOR ACOSTA • DG@FLOPYSYSTEM.COM.AR</span>
	</div>
</footer>